### ISSUE TITLE
Evaluate how to run Java code

### ISSUE THREAD

**Issue by BalestraPatrick** [ASQ-USI-Elements/asq-java-q#5]
Let's keep this issue to discuss our options to run Java code. From my understanding, the service that we use should be as quick and cheap as possible.

- https://www.javapoly.com (discovered by @triglian)

**Comment by marcotollini** [comment]
I have looked at it just a little bit. To me it seems to work well, but it is also seems a little bit slow. I think we should do some benchmarking.
