### ISSUE TITLE
Adapt frontend based on asq-js-eval-q

### ISSUE THREAD

**Issue by BalestraPatrick** [ASQ-USI-Elements/asq-java-q#6]
https://github.com/ASQ-USI-Elements/asq-js-eval-q

**Comment by triglian** [comment]
The frontend will be closer to `asq-code-q` or `asq-sqlite-q`. They use an an `ace-element` element which encapsulates the Ace editor.

 These are the associated lines : 
[asq-code-q](https://github.com/ASQ-USI-Elements/asq-code-q/blob/master/elements/asq-code-q-viewer/asq-code-q-viewer.html#L38)
[asq-sqlite-q](https://github.com/ASQ-USI-Elements/asq-sqlite-q/blob/master/elements/asq-sqlite-q-viewer/asq-sqlite-q-viewer.html#L97)

And this is the bower dependency:  [asq-code-q bower](https://github.com/ASQ-USI-Elements/asq-code-q/blob/master/bower.json#L16)
